// webcomponent/describe.js
const artefact = 'component'
const id = 'card'

const path = 'https://data.dilla.io/bindgen/bootstrap_5/browser/bootstrap_5_dev.js'

class Dilla extends HTMLElement {
  constructor() {
    super()
    this.shadow = this.attachShadow({
      mode: 'open',
    })
  }
  async connectedCallback() {
    const module = await import(path)
    await module.default()
    const result = JSON.parse(module.describe(artefact, id))
    this.shadow.innerHTML = JSON.stringify(result, null, 2)
  }
}

window.customElements.define('dilla-describer', Dilla)

// react/describe.js
const artefact = 'component'
const id = 'card'

const path = "https://data.dilla.io/bindgen/bootstrap_5/browser/bootstrap_5_dev.js"

const Dilla = () => {
  const [rendered, setDillaRender] = React.useState("")

  React.useEffect(() => {
    import(path).then((dilla) => {
      dilla.default()
        .then(() => {
          const result = JSON.parse(dilla.describe(artefact, id))
          setDillaRender(result)
        })
    })
  }, [rendered])

  return <pre>{JSON.stringify(rendered, null, 2)}</pre>
}

const root = ReactDOM.createRoot(document.getElementById('describe'))
root.render(<Dilla />)
