// webcomponent/render.js
const path = 'https://data.dilla.io/bindgen/bootstrap_5/browser/bootstrap_5.js'

const payload = {
  "@component": "alert",
  "@variant": "info",
  heading: "Hello Dilla from JavaScript WebComponents!",
}

class Dilla extends HTMLElement {
  constructor() {
    super()
    this.shadow = document.createElement('iframe')
    this.shadow.style = 'border:none;height:100px;width:100%'
    this.appendChild(this.shadow)
  }
  async connectedCallback() {
    const module = await import(path)
    await module.default()
    let result = module.render(payload)
    this.shadow.contentWindow.document.head.innerHTML = result.system_stylesheet + result.stylesheet
    this.shadow.contentWindow.document.body.innerHTML = '<div class="container mt-4">' + result.body + '</div>'
  }
}

window.customElements.define('dilla-render', Dilla)

// react/render.js
const payload = {
  "@component": "alert",
  "@variant": "info",
  heading: "Hello Dilla from React!",
}

const path = 'https://data.dilla.io/bindgen/bootstrap_5/browser/bootstrap_5.js'

const Dilla = () => {
  const [rendered, setDillaRender] = React.useState('')
  const [dillaIsRendered, setDillaIsRendered] = React.useState(null)
  const renderedHTML = React.useRef(null)

  React.useEffect(() => {
    import(path).then((dilla) => {
      dilla
        .default()
        .then(() => {
          const result = dilla.render(payload)
          setDillaRender(result.body + result.system_stylesheet + result.stylesheet)
        })
        .then(() => {
          setDillaIsRendered(true)
        })
    })
  }, [rendered])

  React.useEffect(() => {
    renderedHTML.current.innerHTML = rendered
  }, [renderedHTML, dillaIsRendered])

  return <div ref={renderedHTML} />
}

const root = ReactDOM.createRoot(document.getElementById('render'))
root.render(<Dilla />)
